name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker for Superlinter
        uses: docker://github/super-linter:4

      - name: Run Superlinter
        run: |
          docker run -e RUN_LOCAL=true -v $(pwd):/tmp/lint github/super-linter:4
